logging:
  level:
    org.springframework.web: debug
    org.springframework.boot: info

server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
  compression:
    enabled: true
  port: 6200
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        use_sql_comments: true
        default_batch_fetch_size: 50
        enable_lazy_load_no_trans: false
        format_sql: true
        dialect:
          storage_engine: innodb
    open-in-view: false

  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 30
      pool-name: SpringBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:6201/local?serverTimezone=Asia/Seoul
    username: local
    password: local


  cloud:
    gateway:
      routes:
        - id: 'river-otter'
          uri: http://localhost:6400
          predicates:
            - Path=/v1/open-api/autostay/**
          filters:
          metadata:
            # swagger를 통해 api 호출시 발급된 token의 allowedServices에 해당 값이 설정되어있어야만 호출할 수 있음, 없으면 401 Unauthorized
            permissionKey: river-otter
            # swagger에 제공할 문서 스펙 가져오는 uri
            documentationUri: http://localhost:6400/v3/api-docs/Open-API

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tags-sorter: alpha

app:
  use-secure-protocol: false
  cache:
    token-clear-interval: 300